version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: loja_db
    ports:
      - ${PORT_MYSQL}:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_db:/var/lib/mysql
      - mysql_db_config:/etc/mysql

  backend:
    container_name: loja_backend
    build:
      context: ./backend
    ports:
      - ${PORT_BACK}:${PORT_BACK}
    volumes:
      - ./backend:/usr/src/app
    env_file: ./backend/.env
    depends_on:
      - db

  frontend:
     container_name: loja_frontend
     build:
       context: ./frontend
     restart: on-failure
     ports:
       - ${PORT_FRONT}:${PORT_FRONT}
     volumes:
       - ./frontend:/usr/src/app
     env_file: ./frontend/.env
     depends_on:
      - backend
      
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - ${PORT_PMA}:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db  
  
volumes:
  mysql_db:
  mysql_db_config:
  # mysql_test:
  # mysql_config_test:
